//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetClinic.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class AdminLogin
    {
        [Required(ErrorMessage = "กรุณากรอกชื่อผู้ใช้")]
        [Display(Name = "ชื่อผู้ใช้งาน")]
        public string Username { get; set; }
        [Required(ErrorMessage = "กรุณากรอกรหัสผ่าน")]
        [Display(Name = "รหัสผ่าน")]

        public string Password { get; set; }
        [Display(Name = "ประภทผู้ใช้งาน")]

        public Nullable<int> Typeuser_ID { get; set; }

        public virtual Table_Typeuser Table_Typeuser { get; set; }
    }
}
