//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetClinic.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PetClinicEntities : DbContext
    {
        public PetClinicEntities()
            : base("name=PetClinicEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdminLogin> AdminLogins { get; set; }
        public virtual DbSet<Table_Owner> Table_Owner { get; set; }
        public virtual DbSet<Table_Pet> Table_Pet { get; set; }
        public virtual DbSet<Table_Promote> Table_Promote { get; set; }
        public virtual DbSet<Table_TypePet> Table_TypePet { get; set; }
        public virtual DbSet<Table_Typeuser> Table_Typeuser { get; set; }
        public virtual DbSet<Table_Visit> Table_Visit { get; set; }
        public virtual DbSet<View_1> View_1 { get; set; }
        public virtual DbSet<View_visit> View_visit { get; set; }
    }
}
