//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetClinic.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Table_Visit
    {
        public int Visit_ID { get; set; }
        public Nullable<int> Pet_ID { get; set; }
        [Display(Name ="วันที่เข้ารักษา")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> VisitDate { get; set; }
        [Display(Name = "รายละเอียดการรักษา")]
        [DataType(DataType.MultilineText)]
        public string Description { get; set; }
        [Display(Name = "วันที่นัดเข้ารักษา")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> NextDate { get; set; }
    
        public virtual Table_Pet Table_Pet { get; set; }
    }
}
