//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetClinic.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Table_Owner
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Table_Owner()
        {
            this.Table_Pet = new HashSet<Table_Pet>();
        }

        public int Owner_ID { get; set; }
        [Display(Name = "ชื่อ")]

        public string Firstname { get; set; }
        [Display(Name = "นามสกุล")]

        public string Lastname { get; set; }
        [Display(Name = "ที่อยู่")]

        public string Address { get; set; }
        [Required(ErrorMessage ="กรุณากรอกเบอร์โทรศัพท์")]
        [Display(Name = "เบอร์โทรศัพท์")]
        [RegularExpression(@"^\(?([0-9]{3})\)?[-. ]?([0-9]{3})[-. ]?([0-9]{4})$",
                   ErrorMessage = "รูปแบบของเบอร์โทรศัพท์ไม่ถูกต้อง")]
        public string Telephone { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Table_Pet> Table_Pet { get; set; }
    }
}
