//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetClinic.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Table_Pet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Table_Pet()
        {
            this.Table_Visit = new HashSet<Table_Visit>();
        }
    
        public int Pet_ID { get; set; }

        [Display(Name ="ชนิดของสัตว์เลี้ยง")]
        public Nullable<int> Type_ID { get; set; }
        [Display(Name = "ชื่อเจ้าของสัตว์")]
        [Required(ErrorMessage ="กรุณากรอกข้อมูล")]

        public Nullable<int> Owner_ID { get; set; }
        [Display(Name = "ชื่อสัตว์เลี้ยง")]
        [Required(ErrorMessage = "กรุณากรอกข้อมูล")]

        public string Pet_Name { get; set; }
        [Display(Name = "อายุ")]

        public Nullable<System.DateTime> Age { get; set; }
        [Display(Name = "เพศ")]

        public string Sex { get; set; }
    
        public virtual Table_Owner Table_Owner { get; set; }
        [Display(Name = "ชนิดของสัตว์เลี้ยง")]


        public virtual Table_TypePet Table_TypePet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Table_Visit> Table_Visit { get; set; }
    }
}
