//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetClinic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_1
    {
        public int Owner_ID { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public string Address { get; set; }
        public string Telephone { get; set; }
        public int Pet_ID { get; set; }
        public string Pet_Name { get; set; }
        public string Sex { get; set; }
        public Nullable<System.DateTime> Age { get; set; }
        public int Type_ID { get; set; }
        public string TypeName { get; set; }
    }
}
